---
- id: sky-villages-forge-fabric
  title: Sky Villages mod compromised with Fracturiser malware
  campaigns:
  - fracturiser-2023
  synopsis: The CurseForge account associated with the 'Sky Villages' Minecraft mod
    was compromised. Attackers uploaded a malicious JAR file appearing as a legitimate
    update for the mod. This file contained the 'Fracturiser' malware, which steals
    various credentials and attempts to infect other JAR files on the victim's computer.
  start_date: 2023-05-01
  end_date: 2023-06-08
  target:
    name: Sky Villages [Forge/Fabric]
    kind: game_mod
  actor:
    name: Cybercriminal Gang
    kind: group
  language: Java
  method:
    cause: compromised_account_credentials
    phase: distribution
    motive: credential_theft
    transitive: false
  impact:
    types:
    - data_exfiltration
  artifacts:
  - id: sky-villages-forge-fabric
    name: Sky Villages [Forge/Fabric]
    kind: binary_archive
    start_date: 2023-05-01
    end_date: 2023-06-08
    locations:
    - uri: https://www.curseforge.com/minecraft/mc-mods/sky-villages-forge-fabric
      role: distribution
    - uri: https://github.com/fractureiser-investigation/fractureiser
      role: mirror
    - uri: https://securelist.com/fracturiser-supply-chain-attack-infecting-minecraft-mods/110014/
      role: mirror
    hashes:
    - sha256:5584ac1f8b713d2f6310bd3cde425b775402fbc70e56e5e8d774bec15703ca79
  references:
  - url: https://support.curseforge.com/en/support/solutions/articles/9000228509-june-2023-infected-mods-detection-tool-and-report
  - url: https://securelist.com/fracturiser-supply-chain-attack-infecting-minecraft-mods/110014/
