---
- id: aws-toolkit-vscode
  title: Malicious script injected into Amazon Q Developer for Visual Studio
  synopsis: A threat actor exploited an inappropriately scoped GitHub token in the
    extension's CodeBuild configuration to commit malicious code into the open-source
    repository. This code was automatically included in the version 1.84.0 release.
    Fortunately, the malicious code failed to execute due to a syntax error.
  start_date: 2025-07-25
  end_date: 2025-07-25
  target:
    name: aws-toolkit-vscode
    kind: plugin
    repo: https://github.com/aws/aws-toolkit-vscode
  actor:
    name: Third Party
    kind: group
  language: TypeScript
  method:
    cause: compromised_credentials
    phase: source
    motive: malicious
    transitive: false
  impact:
    types:
    - none
    users: 0
  artifacts:
  - id: aws-toolkit-vscode
    name: aws-toolkit-vscode
    kind: extension
    repo: https://github.com/aws/aws-toolkit-vscode
    start_date: 2025-07-25
    end_date: 2025-07-25
    versions:
    - 1.84.0
    locations:
    - uri: https://github.com/aws/aws-toolkit-vscode
      role: mirror
    hashes:
    - sha256:47f7840ecab6312d2733e1274c513050405886c70f2037fb2f1e9099872b0464
  references:
  - url: https://github.com/aws/aws-toolkit-vscode/security/advisories/GHSA-7g7f-ff96-5gcw
