- name: got-fetch
  title: "got-fetch npm Package Hijacked (Scavenger Malware)"
  repo: https://github.com/sindresorhus/got-fetch
  synopsis: "As part of an expanding supply chain attack tied to the npnjs.com phishing campaign, attackers published rogue versions of got-fetch. The malware, dubbed Scavenger, stole browser data and credentials, and provided remote access via WebSocket."
  start_date: 2025-07-18
  end_date: 2025-07-22
  attribution_type: Third Party
  component_type: Library
  lang: JavaScript
  cause: Compromised Account/Credentials
  motive: Data Exfiltration/Remote Access
  transitive: false
  historical_artifacts: []
  current_artifacts: []
  domain: npmjs.com
  domain_type: package host
  artifact_type: source archive
  insertion_phase: distribution
  impact_type: Remote Access/Credential Theft
  impact_user_count: 0
  references:
    - https://socket.dev/blog/npm-is-package-hijacked-in-expanding-supply-chain-attack
  versions:
    - 5.1.11
    - 5.1.12
  commits: []
  hashes: []
