---
- id: strong-password
  title: strong_password Ruby gem compromised with backdoor code
  synopsis: Similar to the 'rest-client' incident around the same time, the 'strong_password'
    Ruby gem had a malicious version published. This compromised version contained
    a backdoor designed to steal environment variables and potentially execute code.
    It's suspected the same actor compromised both gems.
  start_date: 2019-08-16
  end_date: 2019-08-21
  target:
    name: strong_password
    kind: library
  actor:
    name: Individual Hacker
    kind: person
  language: Ruby
  method:
    cause: compromised_account_credentials
    phase: distribution
    motive: credential_theft
    transitive: false
  impact:
    types:
    - data_exfiltration
  artifacts:
  - id: strong-password
    name: strong_password
    kind: source_archive
    start_date: 2019-08-16
    end_date: 2019-08-21
    versions:
    - 0.0.7
    locations:
    - uri: https://rubygems.org/gems/strong_password/versions/0.0.7
      role: distribution
    - uri: https://rubygems.org/downloads/strong_password-0.0.7.gem
      role: distribution
    - uri: https://snyk.io/blog/code-execution-back-door-found-in-rubys-rest-client-library/
      role: mirror
    - uri: https://www.helpnetsecurity.com/2019/08/21/backdoored-ruby-gems/
      role: mirror
    hashes:
    - sha256:c3a46b979b941ecc456639033754f3bad3f5d379df064d4ccd0b54d0fb8e46ea
  references:
  - url: https://github.com/rest-client/rest-client/issues/713
  - url: https://snyk.io/blog/code-execution-back-door-found-in-rubys-rest-client-library/
  - url: https://www.helpnetsecurity.com/2019/08/21/backdoored-ruby-gems/
