- name: eslint
  title: eslint-scope/config-eslint NPM compromise steals NPM tokens
  repo: https://github.com/eslint/eslint-scope
  synopsis: An attacker compromised the npm account of an ESLint maintainer and published malicious versions of eslint-scope and eslint-config-eslint. The injected code searched developer machines for .npmrc authentication tokens, aiming to turn one trusted maintainer account into many future publishing keys.
  start_date: 2018-07-12
  end_date: 2018-07-12
  attribution_type: Individual Hacker
  component_type: Library # Development Tooling
  lang: Javascript
  cause: Compromised Account/Credentials
  motive: Credential Theft # Access NPM accounts
  transitive: false
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  insertion_phase: distribution
  impact_type: Data Exfiltration
  impact_user_count: 4500 # Estimated downloads during the compromised window
  references:
    - https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes/ # ESLint Postmortem
    - https://github.com/eslint/eslint-scope/issues/39 # Initial GitHub issue reporting the compromise
    - https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm # NPM Blog Post on related attack vector
  versions:
    - eslint-scope@3.7.2
    - eslint-config-eslint@5.0.2
  historical_artifacts:
    - https://registry.npmjs.org/eslint-scope/-/eslint-scope-3.7.2.tgz
    - https://registry.npmjs.org/eslint-config-eslint/-/eslint-config-eslint-5.0.2.tgz # Also compromised
  current_artifacts:
    - https://github.com/eslint/eslint-scope/issues/39 # GitHub issue with details of the malicious code
    - https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes/ # ESLint postmortem with attack details
    - https://snyk.io/vuln/npm:eslint-scope:20180712 # Snyk advisory with technical details
  hashes:
    - sha256:ecdf72a1e1a4cfb67e220c827b2a7613cf8b0280cac0936879a2c12398897ce4 # eslint-scope-3.7.2.tgz
    - sha256:b208f83f1e4e3a3273d59acf970cb9678e8b46554bee2b2034675038b25ac15c # eslint-config-eslint-5.0.2.tgz
