---
- id: transmission-2016-08
  title: Transmission macOS installer distributed Keydnap backdoor
  synopsis: Months after the KeRanger incident, Transmission's website was compromised
    again. This time, the legitimate macOS installer for version 2.92 was replaced
    with a malicious version containing the OSX/Keydnap backdoor. Keydnap aimed to
    steal keychain credentials and establish persistent remote access.
  start_date: 2016-08-28
  end_date: 2016-08-30
  target:
    name: transmission
    kind: application
    website: https://transmissionbt.com
    repo: https://github.com/transmission/transmission
  actor:
    name: Cybercriminal Gang
    kind: group
  language: Binary
  method:
    cause: compromised_infrastructure
    phase: distribution
    motive: credential_theft
    transitive: false
  impact:
    types:
    - data_exfiltration
  artifacts:
  - id: transmission-2016-08
    name: transmission
    kind: binary_archive
    website: https://transmissionbt.com
    repo: https://github.com/transmission/transmission
    start_date: 2016-08-28
    end_date: 2016-08-30
    versions:
    - 2.92
    locations:
    - uri: https://download.transmissionbt.com/files/Transmission-2.92.dmg
      role: distribution
    - uri: https://updates.transmissionbt.com/Transmission-2.92.dmg
      role: distribution
    - uri: https://objective-see.org/blog/blog_0x11.html
      role: mirror
    - uri: https://www.welivesecurity.com/2016/08/30/osxkeydnap-spreads-via-signed-transmission-application/
      role: mirror
    hashes:
    - sha256:f06ac9609c3a8b00a7586840e990153460f8de9526e91a1a6ab733c850d5c83f
    - sha256:c5e5ec89c5517b50d848b6a6d4f86ed74715a715a015c6d38d789addcffea6b3
  references:
  - url: https://objective-see.org/blog/blog_0x11.html
