- name: aws-toolkit-vscode
  title: Malicious script injected into Amazon Q Developer for Visual Studio
  repo: https://github.com/aws/aws-toolkit-vscode
  synopsis: A threat actor exploited an inappropriately scoped GitHub token in the extension's CodeBuild configuration to commit malicious code into the open-source repository. This code was automatically included in the version 1.84.0 release. Fortunately, the malicious code failed to execute due to a syntax error.
  start_date: 2025-07-25
  end_date: 2025-07-25
  attribution_type: Third Party
  component_type: Plugin
  lang: TypeScript
  cause: Compromised Credentials
  motive: Malicious
  transitive: false
  historical_artifacts: []
  current_artifacts: []
  domain: marketplace.visualstudio.com
  domain_type: package host
  artifact_type: extension
  insertion_phase: source
  impact_type: None
  impact_user_count: 0
  references:
    - https://github.com/aws/aws-toolkit-vscode/security/advisories/GHSA-7g7f-ff96-5gcw
  versions:
    - 1.84.0
  commits: []
  hashes:
    - "sha256:47f7840ecab6312d2733e1274c513050405886c70f2037fb2f1e9099872b0464"
