---
- id: node-ipc
  title: node-ipc NPM package maintainer adds protestware malware
  synopsis: The maintainer added protestware to node-ipc, a widely used interprocess
    communication library, targeting users resolving from Russian or Belarusian IP
    addresses. The code attempted to recursively overwrite files with a heart character
    during normal package use, turning geopolitical protest into selective data destruction
    that could ripple through dependent JavaScript applications.
  start_date: 2022-03-07
  end_date: 2022-03-16
  target:
    name: node-ipc
    kind: library
    repo: https://github.com/RIAEvangelist/node-ipc
  actor:
    name: Author
    kind: maintainer
  language: Javascript
  method:
    cause: sabotage
    phase: source
    motive: disruption_protest
    transitive: false
  impact:
    types:
    - service_disruption
    - data_destruction
    users: 1000000
  artifacts:
  - id: node-ipc
    name: node-ipc
    kind: source_archive
    repo: https://github.com/RIAEvangelist/node-ipc
    start_date: 2022-03-07
    end_date: 2022-03-16
    versions:
    - 9.2.2
    - 10.1.1
    - 10.1.2
    - 11.0.0
    locations:
    - uri: https://registry.npmjs.org/node-ipc/-/node-ipc-9.2.2.tgz
      role: distribution
    - uri: https://registry.npmjs.org/node-ipc/-/node-ipc-10.1.1.tgz
      role: distribution
    - uri: https://registry.npmjs.org/node-ipc/-/node-ipc-10.1.2.tgz
      role: distribution
    - uri: https://registry.npmjs.org/node-ipc/-/node-ipc-11.0.0.tgz
      role: distribution
    - uri: https://snyk.io/blog/peacenotwar-protestware-node-ipc-package-vulnerability/
      role: mirror
    - uri: https://github.com/RIAEvangelist/node-ipc/commit/f3ff376905550597f05410771031cc67a446f662
      role: mirror
    - uri: https://socket.dev/npm/package/node-ipc/versions
      role: mirror
    hashes:
    - sha256:f54bb89fe21762ce2ab5fe7581bf7f347f79ec30abe3ab1175da4edc26b5f91a
    - sha256:03190b659f9ad3c0e0bb337a958cbfa49c0bbfd8baff63d5a178c0eb6c8ea292
    commits:
    - f3ff376905550597f05410771031cc67a446f662
  references:
  - url: https://snyk.io/blog/peacenotwar-protestware-node-ipc-package-vulnerability/
  - url: https://github.com/advisories/GHSA-97m3-w2cp-4xx6
  - url: https://arstechnica.com/information-technology/2022/03/sabotage-code-added-to-popular-npm-package-wiped-files-in-russia-and-belarus/
