---
- id: agama
  title: Agama wallet compromised via malicious dependency backdoor
  synopsis: The Agama cryptocurrency wallet application inadvertently included a compromised
    version of the `electron-native-notify` NPM package (v1.1.6) as a dependency in
    its builds. This resulted in official Agama wallet releases containing a backdoor
    (reverse shell) inherited from the dependency, potentially allowing attackers
    remote access and theft of wallet seeds or private keys.
  start_date: 2018-08-01
  end_date: 2018-08-13
  target:
    name: agama
    kind: application
    repo: https://github.com/KomodoPlatform/Agama
  actor:
    name: Compromised Dependency
    kind: dependency
  language: Javascript
  method:
    cause: malicious_dependency
    phase: dependency
    motive: financial_gain
    transitive: true
  impact:
    types:
    - backdoor
    - remote_code_execution
  artifacts:
  - id: agama
    name: agama
    ecosystem: github
    kind: binary_archive
    website: https://github.com
    repo: https://github.com/KomodoPlatform/Agama
    start_date: 2018-08-01
    end_date: 2018-08-13
    versions:
    - 0.3.3
    - 0.3.4
    locations:
    - uri: https://github.com/eslint/eslint-scope/issues/39
      role: mirror
    - uri: https://github.com/eslint/eslint-scope/issues/39#issuecomment-404461211
      role: mirror
    - uri: https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm
      role: mirror
    hashes:
    - sha256:07f16d95f3c91dbd2ddf974d4b95d8dcec39b09b8906fa3b35e0a0da78fe8f76
    indicators:
    - kind: observable
      value: v0.3.3
    - kind: observable
      value: v0.3.4
  references:
  - url: https://komodoplatform.com/vulnerability-discovered-in-komodos-agama-wallet-this-is-what-you-need-to-do/
  - url: https://github.com/eslint/eslint-scope/issues/39
  - url: https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm
