---
- id: copay
  title: Event-stream dependency compromised Copay wallet
  synopsis: The Copay Bitcoin wallet was pulled into the event-stream compromise through
    a malicious npm dependency. The injected code specifically recognized Copay workflows
    and attempted to steal wallet secrets, making a transitive JavaScript library
    the narrow blade against cryptocurrency users and their funds.
  start_date: 2018-09-09
  end_date: 2018-11-26
  target:
    name: Copay
    kind: application
    website: https://copay.io
    repo: https://github.com/bitpay/copay
  actor:
    name: Individual Hacker
    kind: person
  language: JavaScript
  method:
    cause: compromised_dependency
    phase: dependency
    motive: financial_gain
    transitive: true
  impact:
    types:
    - cryptocurrency_theft
    users: 1000000
  artifacts:
  - id: copay
    name: Copay
    kind: binary_archive
    website: https://copay.io
    repo: https://github.com/bitpay/copay
    start_date: 2018-09-09
    end_date: 2018-11-26
    versions:
    - 5.0.2
    - 5.1.0
    locations:
    - uri: https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
      role: distribution
    - uri: https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.1.tgz
      role: distribution
    - uri: https://github.com/bitpay/copay/releases/tag/v5.0.2
      role: distribution
    - uri: https://github.com/bitpay/copay/releases/tag/v5.1.0
      role: distribution
    - uri: https://github.com/dominictarr/event-stream/issues/116
      role: mirror
    - uri: https://gist.github.com/thejoshwolfe/38f4c4a98208300ab903f81f0a5004d9
      role: mirror
    - uri: https://my.diffend.io/npm/flatmap-stream/0.1.0/0.1.1
      role: mirror
    hashes:
    - sha256:005a6cfb72127d0007798d72700e28df0b5280b9f7e56f355de65a8f9107026e
    commits:
    - 470d7c7395001440f0187550297cf083d52c43a6
    indicators:
    - kind: observable
      value: 3.3.6
    - kind: observable
      value: 0.1.1
  references:
  - url: https://bitpay.com/blog/statement-on-compromised-copay-resources/
  - url: https://medium.com/coinmonks/the-anatomy-of-a-supply-chain-attack-on-the-javascript-ecosystem-ee650cd8740
