- name: colors.js
  title: colors.js NPM package maintainer sabotage breaks apps
  campaigns:
    - faker-colors-sabotage-2022
  repo: https://github.com/Marak/colors.js
  synopsis: The maintainer intentionally introduced an infinite loop and breaking changes into colors.js, a tiny library with millions of weekly downloads. The protest act printed strange characters, broke dependent applications, and caused denial of service in normal startup paths. Its impact came from dependency gravity; small utilities can sit beneath enormous production surfaces.
  start_date: 2022-01-07
  end_date: 2022-01-09
  attribution_type: Author
  component_type: Library
  lang: Javascript
  cause: Sabotage
  motive: Disruption/Protest
  transitive: false
  historical_artifacts:
    - https://registry.npmjs.org/colors/-/colors-1.4.1.tgz
    - https://registry.npmjs.org/colors/-/colors-1.4.2.tgz
    - https://registry.npmjs.org/colors/-/colors-1.4.44-liberty-2.tgz
  current_artifacts:
    - https://web.archive.org/web/20220109100152/https://github.com/Marak/colors.js/blob/master/lib/index.js # Archive of affected code
    - https://socket.dev/npm/package/colors/files/1.4.1/lib/index.js # Socket archive showing malicious code
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  insertion_phase: source
  impact_type: Service Disruption, Data Destruction
  impact_user_count: 2000000 # Based on weekly downloads around the time
  references:
    - https://github.com/Marak/colors.js/issues/285
    - https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/
  versions:
    - 1.4.1
    - 1.4.2
    - 1.4.44-liberty-2
  commits:
    - d11691a1a694899d8a543f027a368426350a2969 # Initial commit with breaking changes
    - 6bc50e799061788799a73579c07683b499906d29 # Second commit with infinite loop
    - 8d817695d1e57a8011ba373d896985758850f03c # Final sabotage commit
  hashes:
    - "sha256:5bc0d3d47b85c20241bfb5a014f9c670db195b1341ee3f91c69b2243e6b7711c" # colors-1.4.1.tgz
    - "sha256:764ff5d6f472e97de7196747741b9c4bc51186e9bf57690f4e68311df1ecfe92" # colors-1.4.2.tgz
    - "sha256:c4175e9eecf0fb963b99e2d51a6f16bc8daf68c74378481a99092c8bb49c0b28" # colors-1.4.44-liberty-2.tgz
