- name: DAEMON Tools
  title: Trojanized DAEMON Tools distributed QUIC RAT.
  synopsis: Attackers compromised official installers for DAEMON Tools, a popular disk imaging software, to distribute multi-stage malware. The infection chain included an information collector and a complex "QUIC RAT" backdoor, which was used for targeted espionage against government and scientific organizations globally.
  start_date: 2026-04-08
  end_date: Ongoing
  attribution_type: Chinese-speaking actor
  component_type: Application
  lang: C++
  cause: Website compromise
  motive: Espionage
  transitive: false
  insertion_phase: distribution
  impact_type: Backdoor, Data theft, Remote access
  impact_user_count: 50000
  references:
    - https://securelist.com/tr/daemon-tools-backdoor/119654/
  versions:
    - 12.5.0.2421
    - 12.5.0.2425
    - 12.5.0.2429
    - 12.5.0.2432
    - 12.5.0.2434
  historical_artifacts:
    - https://files.disc-soft.com/inst/DTLite64.exe
  current_artifacts:
    - https://www.virustotal.com/gui/file/10d9e84307f0f62d186e24508499252327702f30691456a2976be04d603a1168
    - https://www.virustotal.com/gui/file/2d4eb55b01f59c62c6de9aacba9b47267d398fe4
    - https://www.virustotal.com/gui/file/b58557997380907d7301018568c07d3967d337894a8607a016667b1654860f4e
  domain: daemontools.cc
  domain_type: project download host
  artifact_type: binary archive
  hashes:
    - sha1:9ccd769624de98eeeb12714ff1707ec4f5bf196d
    - sha1:2d4eb55b01f59c62c6de9aacba9b47267d398fe4
    - sha1:396041ec1838836528d227d896683884c7188173
    - sha256:10d9e84307f0f62d186e24508499252327702f30691456a2976be04d603a1168
    - sha256:b58557997380907d7301018568c07d3967d337894a8607a016667b1654860f4e
