---
- id: mailparser
  title: mailparser NPM package compromised downloads executes binary
  synopsis: The maintainer's npm account for mailparser was compromised, and malicious
    version 0.1.2 was published to the registry. Its install path attempted to download
    and execute an OS-specific binary from an external server, but the package was
    removed within an hour and saw fewer than 100 downloads.
  start_date: 2019-03-12
  end_date: 2019-03-12
  target:
    name: mailparser
    kind: library
    repo: https://github.com/mailparser-legacy/mailparser
  actor:
    name: Individual Hacker
    kind: person
  language: Javascript
  method:
    cause: compromised_account_credentials
    phase: distribution
    motive: unauthorized_access_control
    transitive: false
  impact:
    types:
    - backdoor
    - remote_code_execution
    users: 100
  artifacts:
  - id: mailparser
    name: mailparser
    kind: source_archive
    repo: https://github.com/mailparser-legacy/mailparser
    start_date: 2019-03-12
    end_date: 2019-03-12
    versions:
    - 0.1.2
    locations:
    - uri: https://registry.npmjs.org/mailparser/-/mailparser-0.1.2.tgz
      role: distribution
    - uri: https://security.snyk.io/vuln/npm:mailparser:20190312
      role: mirror
    hashes:
    - sha256:a7c55ef358ba3b90def7f46fd0ad40830e0df3b6f68e32cdb8603c4ccb0cc45a
  references:
  - url: https://security.snyk.io/vuln/npm:mailparser:20190312
  - url: https://www.npmjs.com/advisories/912
