- name: Aisino
  title: Chinese tax software installed GoldenSpy backdoor.
  synopsis: "Intelligent Tax software, produced by Aisino Corporation and required by some Chinese banks for companies operating in China, was found to install the GoldenSpy backdoor. This malware provided extensive remote access and control capabilities, including command execution and data exfiltration, with a delayed installation to evade detection."
  start_date: 2020-04-01 # Approximate start of the GoldenSpy campaign via Aisino software (earlier related GoldenHelper from 2018)
  end_date: 2020-06-28 # Approximate date an uninstaller for GoldenSpy was pushed after public disclosure
  attribution_type: Nation-state
  component_type: Application # Tax software
  cause: Vendor compromise # Or complicity, embedded in official software
  motive: Espionage, Data theft
  transitive: false
  insertion_phase: source # Malware embedded within the legitimate, required tax software installer
  impact_type: Backdoor
  impact_user_count: 1000 # Estimate, targeted foreign companies operating in China
  references:
    - https://www.zdnet.com/article/chinese-bank-forced-western-companies-to-install-malware-laced-tax-software/
    - https://attack.mitre.org/software/S0493/
    - https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/goldenspy-whos-really-pulling-the-strings/
    - https://www.crowdstrike.com/blog/goldenspy-supply-chain-attack-hits-organizations-operating-in-china/
  versions:
    - "Multiple versions of Aisino Intelligent Tax software containing GoldenSpy module, active in 2020"
  domain: i-xinnuo.com # Aisino's software domain (initial download point)
  domain_type: project download host
  artifact_type: binary archive # Installer for tax software
  historical_artifacts:
    - http://download.i-xinnuo.com/products/IntelligentTaxSetup.exe
  current_artifacts:
    - "https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/goldenspy-whos-really-pulling-the-strings/"
    - "https://www.virustotal.com/gui/file/c1d7873a21d28ba995725f958741948f0d750b1e18311341682b56f257025642" # svm.exe (GoldenSpy payload)
    - "https://www.virustotal.com/gui/file/1536924c856093919f4f697f83225471094e4868131226a996d75a738080b0e6" # svm.exe (GoldenSpy payload variant)
    - "https://www.virustotal.com/gui/file/5953fc590db6ab347840ccbf10f09a0b1bb48d38309067a1d65c34cb3ce82f4b" # PluginManager.exe (Dropper component)
    - "https://bazaar.abuse.ch/browse.php?search=tag%3AGoldenSpy"
  hashes:
    - sha256:c1d7873a21d28ba995725f958741948f0d750b1e18311341682b56f257025642 # svm.exe (GoldenSpy main payload)
    - sha256:1536924c856093919f4f697f83225471094e4868131226a996d75a738080b0e6 # another svm.exe variant (GoldenSpy main payload)
    - sha256:5953fc590db6ab347840ccbf10f09a0b1bb48d38309067a1d65c34cb3ce82f4b # PluginManager.exe (Dropper component for GoldenSpy)
    - sha256:aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899
