---
- id: wp-social-warfare
  title: WordPress.org Supply Chain Attack on Social Warfare
  campaigns:
  - wordpress-plugin-backdoor-2024
  synopsis: Malicious code was injected directly into the Social Warfare plugin repository
    on WordPress.org. The malware created a new administrative user account (Options
    or PluginAuth) to gain full administrative control over affected sites and injected
    malicious JavaScript into website footers to generate SEO spam.
  start_date: 2024-06-21
  end_date: 2024-06-24
  target:
    name: wp-social-warfare
    kind: plugin
    repo: https://wordpress.org/plugins/social-warfare/
  actor:
    name: Third Party
    kind: group
  language: PHP
  method:
    cause: malicious_injection
    phase: source
    motive: seo_spam_account_takeover
    transitive: false
  impact:
    types:
    - account_takeover
    - defacement
    users: 0
  artifacts:
  - id: wp-social-warfare
    name: wp-social-warfare
    kind: extension
    repo: https://wordpress.org/plugins/social-warfare/
    start_date: 2024-06-21
    end_date: 2024-06-24
    versions:
    - 4.4.6.4
    - 4.4.7.1
    locations:
    - uri: https://wordpress.org/plugins/social-warfare/
      role: mirror
  references:
  - url: https://www.wordfence.com/blog/2024/06/supply-chain-attack-on-wordpress-org-plugins-leads-to-5-maliciously-compromised-wordpress-plugins/
