---
- id: magento-extensions
  title: Magento extensions backdoored in coordinated supply chain attack.
  synopsis: Servers of multiple Magento extension vendors (including Tigren, Meetanshi,
    MGS) were compromised. Attackers injected PHP backdoors into at least 21 popular
    commercial extensions. The backdoors, some dormant for years but activated in
    2025, allowed remote code execution on e-commerce stores using the compromised
    extensions.
  start_date: 2019-01-01
  end_date: 2025-04-20
  target:
    name: Magento Extensions
    kind: library
  actor:
    name: Unknown
    kind: unknown
  method:
    cause: vendor_server_compromise
    phase: distribution
    motive: remote_access
    transitive: false
  impact:
    types:
    - backdoor
    - remote_access
    - data_theft_potential
    users: 1000
  artifacts:
  - id: magento-extensions
    name: Magento Extensions
    kind: source_archive
    start_date: 2019-01-01
    end_date: 2025-04-20
    locations:
    - uri: https://tigren.com/m2/extensions/tigren-ajax-cart.zip
      role: distribution
    - uri: https://meetanshi.com/media/downloads/Meetanshi_SocialLogin-2.0.5.zip
      role: distribution
    - uri: https://magesolution.com/downloads/MGS_Fbuilder_v2.2.1.zip
      role: distribution
    - uri: https://sansec.io/research/magento-supply-chain-attack-vendor-extensions
      role: mirror
    - uri: https://twitter.com/gwillem/status/1519986321786552321
      role: mirror
    - uri: https://github.com/gwillem/magento-malware-scanner/blob/master/rules/backend.txt
      role: mirror
    hashes:
    - sha256:e8edc2b931eb5b24a6fdc705add5685ab88e268d7c5179cb42c235a8192b10c1
    - md5:c8ed5ee17d5c95dbe8a9c3c73dc7043c
    notes:
    - Affected Magento scope covered multiple versions of more than 21 extensions
      from vendors including Tigren, Meetanshi, MGS, and potentially Weltpixel.
  references:
  - url: https://www.bleepingcomputer.com/news/security/magento-supply-chain-attack-compromises-hundreds-of-e-stores/
  - url: https://sansec.io/research/magento-supply-chain-attack-vendor-extensions
  - url: https://gbhackers.com/hackers-exploit-21-apps-to-take-full-control/
