- name: ledger-connect-kit
  title: Ledger Connect Kit Supply Chain Attack
  repo: https://github.com/LedgerHQ/connect-kit
  synopsis: A former Ledger employee fell victim to a phishing attack, allowing attackers to access their NPM account and publish malicious versions of the @ledgerhq/connect-kit package. The payload contained a drainer that rerouted cryptocurrency funds to the attacker, affecting major dApps like SushiSwap and Revoke.cash.
  start_date: 2023-12-14
  end_date: 2023-12-14
  attribution_type: Third Party
  component_type: Library
  lang: JavaScript
  cause: Compromised Account/Credentials
  motive: Financial gain
  transitive: true
  historical_artifacts: []
  current_artifacts: []
  domain: npmjs.com
  domain_type: package host
  artifact_type: source archive
  insertion_phase: distribution
  impact_type: Financial Exploitation
  impact_user_count: 500000
  references:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-49954
  versions:
    - 1.1.5
    - 1.1.6
    - 1.1.7
  commits: []
  hashes: []
