---
- id: android-triada
  title: Android firmware shipped with sophisticated Triada trojan.
  synopsis: The complex, modular Triada trojan was repeatedly found pre-installed
    deep within the firmware (sometimes infecting core Android processes like Zygote
    or system libraries) of numerous, often budget or counterfeit, Android devices.
    This likely occurred via supply chain compromise during manufacturing or firmware
    integration, granting attackers persistent, high-privilege access for credential
    theft, app modification, financial fraud, and further malware delivery.
  start_date: 2016-01-01
  end_date: Ongoing
  target:
    name: Android/Triada
    kind: firmware
  actor:
    name: Cybercriminal group
    kind: group
  method:
    cause: manufacturing_compromise
    phase: ci_cd
    motive: financial_gain_credential_theft_account_takeover
    transitive: false
  impact:
    types:
    - backdoor
    - rootkit
    - data_theft
    - credential_theft
    - fraud
    users: 1000000
  artifacts:
  - id: android-triada
    name: Android/Triada
    kind: hardware
    start_date: 2016-01-01
    end_date: Ongoing
    locations:
    - uri: pkg://android/com.android.system.DataStorage
      role: distribution
    - uri: https://securelist.com/triada-trojan-modules-analysis/116380/#indicators-of-compromise
      role: mirror
    - uri: https://raw.githubusercontent.com/adrdotocet/ott/main/api.json
      role: mirror
    - uri: https://raw.githubusercontent.com/adrdotocet2/ott/main/api.json
      role: mirror
    - uri: https://raw.githubusercontent.com/adrdotocet3/ott/main/api.json
      role: mirror
    - uri: https://bazaar.abuse.ch/browse.php?search=tag%3ATriada
      role: mirror
    hashes:
    - md5:f468a29f836d2bba7a2b1a638c5bebf0
    - md5:89c3475be8dba92f4ee7de0d981603c1
    - md5:fce117a9d7c8c73e5f56bda7437bdb28
    - md5:308e35fb48d98d9e466e4dfd1ba6ee73
    indicators:
    - kind: observable
      value: Embedded in firmware of counterfeit/unbranded Android devices during
        manufacturing.
    notes:
    - Affected Android Triada scope covered numerous budget, unbranded, and counterfeit
      Android device firmware builds.
  references:
  - url: https://securelist.com/triada-trojan-modules-analysis/116380/
  - url: https://source.android.com/docs/security/reports/Google_Android_Security_2018_Report_Final.pdf
  - url: https://thehackernews.com/2025/04/triada-malware-preloaded-on-counterfeit.html
  - url: https://news.drweb.com/show/?i=10451
