- name: wp-blaze-widget
  title: WordPress.org Supply Chain Attack on Blaze Widget
  repo: https://wordpress.org/plugins/blaze-widget/
  synopsis: Malicious code was injected directly into the Blaze Widget plugin repository on WordPress.org. The malware created a new administrative user account (Options or PluginAuth) to gain full administrative control over affected sites and injected malicious JavaScript into website footers to generate SEO spam.
  start_date: 2024-06-21
  end_date: 2024-06-24
  attribution_type: Third Party
  component_type: Plugin
  lang: PHP
  cause: Malicious Injection
  motive: SEO Spam/Account Takeover
  transitive: false
  historical_artifacts: []
  current_artifacts: []
  domain: wordpress.org
  domain_type: package host
  artifact_type: extension
  insertion_phase: source
  impact_type: Account Takeover/Defacement
  impact_user_count: 0
  references:
    - https://www.wordfence.com/blog/2024/06/supply-chain-attack-on-wordpress-org-plugins-leads-to-5-maliciously-compromised-wordpress-plugins/
  versions:
    - 2.2.5
    - 2.5.2
  commits: []
  hashes: []
