---
- id: evlog
  title: Altair EvLog update delivered Kingslayer malware.
  synopsis: Attackers compromised update mechanisms for Altair Technologies' EvLog
    event log management software. Altered versions, signed with a stolen private
    key, were distributed containing the 'Kingslayer' malware which provided backdoor
    access, targeting telecom and military organizations primarily between April and
    July 2015.
  start_date: 2015-04-01
  end_date: 2015-07-31
  target:
    name: EvLog
    kind: application
    website: https://altairtech.com
  actor:
    name: Unknown attacker
    kind: unknown
  method:
    cause: stolen_certificates_keys
    phase: distribution
    motive: espionage
    transitive: false
  impact:
    types:
    - backdoor
    - remote_access
    - credential_theft
    users: 100
  artifacts:
  - id: evlog
    name: EvLog
    kind: binary_archive
    website: https://altairtech.com
    start_date: 2015-04-01
    end_date: 2015-07-31
    locations:
    - uri: https://web.archive.org/web/20170726040823/https://www.comsecglobal.com/kingslayer-a-supply-chain-attack/
      role: mirror
    hashes:
    - sha256:caea901a301b9c103d90b8539819e050e57b67c6ff4d7863ad1cd549f5fdc2af
    - sha256:383d60bffd5dc64e38893361cb03939bc8c6d5e476dc70755eb0886947e51661
    - sha256:7aa474d0d39a41768149f413c451e9208f73af4d262b6575ada31644f5699153
    - sha256:15113f237b29f51c78f315db7d815c5ed1340f52b500f66979edb153515910d7
    - sha256:72ccf28f4636403249d87721e802140ccae2248b810860f8c5d4f33d07363597
    - sha256:4286ecd104cf0667064ad008e5ac9ffa33a0f7858bb745d533fdb30369e89dd4
    indicators:
    - kind: observable
      value: Compromised EvLog update packages distributed via Altair Technologies'
        official update channels.
    notes:
    - Affected EvLog scope covered versions updated between April and July 2015.
  references:
  - url: https://web.archive.org/web/20170726040823/https://www.comsecglobal.com/kingslayer-a-supply-chain-attack/
  - url: https://securityaffairs.com/58864/cyber-crime/operation-wilysupply-hacking.html
