---
- id: rand-user-agent
  title: rand-user-agent Package Hijacked With RAT
  synopsis: Attackers compromised the NPM account of the maintainer and published
    malicious versions of the rand-user-agent package. The compromised versions contained
    obfuscated code that installed a Remote Access Trojan (RAT), which established
    a connection to a command-and-control server. The malware could execute arbitrary
    commands, upload files from victims' machines, and modify the PATH environment
    variable to hijack Python execution.
  start_date: 2025-05-05
  end_date: 2025-05-05
  target:
    name: rand-user-agent
    kind: library
    repo: https://github.com/WebScrapingAPI/rand-user-agent
  actor:
    name: Individual Hacker
    kind: person
  language: JavaScript
  method:
    cause: compromised_account_credentials
    phase: distribution
    motive: unauthorized_access_control
    transitive: false
  impact:
    types:
    - backdoor
    - remote_code_execution
    users: 45000
  artifacts:
  - id: rand-user-agent
    name: rand-user-agent
    kind: source_archive
    repo: https://github.com/WebScrapingAPI/rand-user-agent
    start_date: 2025-05-05
    end_date: 2025-05-05
    versions:
    - 1.0.110
    - 2.0.83
    - 2.0.84
    locations:
    - uri: https://registry.npmjs.org/rand-user-agent/-/rand-user-agent-1.0.110.tgz
      role: distribution
    - uri: https://registry.npmjs.org/rand-user-agent/-/rand-user-agent-2.0.83.tgz
      role: distribution
    - uri: https://registry.npmjs.org/rand-user-agent/-/rand-user-agent-2.0.84.tgz
      role: distribution
    - uri: https://www.aikido.dev/blog/catching-a-rat-remote-access-trojian-rand-user-agent-supply-chain-compromise
      role: mirror
    hashes:
    - sha256:4ecdf8ceee1f2345ef9996c15f44eee3f87a1e04baa0fb0f91cc228e699a2873
  references:
  - url: https://www.aikido.dev/blog/catching-a-rat-remote-access-trojian-rand-user-agent-supply-chain-compromise
  - url: https://www.npmjs.com/package/rand-user-agent
