---
- id: anydesk
  title: AnyDesk Production Environment Breach (2024)
  synopsis: AnyDesk disclosed a breach of its production systems resulting in the theft of source code and private code-signing certificates. While not a ransomware attack, the stolen certificates were later used by threat actors to sign malware (such as Agent Tesla) as legitimate AnyDesk software.
  start_date: 2024-01-29
  end_date: 2024-02-02
  target:
    name: anydesk
    kind: application
    website: https://anydesk.com
  actor:
    name: Third Party
    kind: group
  language: C++
  method:
    cause: system_compromise
    phase: production
    motive: espionage
    transitive: false
  impact:
    types:
    - data_leak
    - certificate_theft
    users: 18000
  artifacts:
  - id: anydesk
    name: anydesk
    kind: application
    website: https://anydesk.com
    start_date: 2024-01-29
    end_date: 2024-02-02
  references:
  - url: https://thehackernews.com/2024/02/anydesk-hit-by-cyber-attack-hackers.html
