- name: wuftpd
  title: wu-ftpd source distribution trojaned with backdoor
  synopsis: The source code distribution for the popular wu-ftpd FTP server was modified by an attacker to include a backdoor. This trojaned version was then uploaded to the primary distribution site. The backdoor allowed attackers who knew the trigger mechanism to gain root privileges on systems that compiled and ran the compromised server.
  start_date: 1994-03-28 # Date trojaned version discovered
  end_date: 1994-03-28 # Quickly identified and replaced
  attribution_type: Individual Hacker
  component_type: Daemon # FTP Server
  lang: C
  cause: Compromised Infrastructure # Primary distribution site hacked
  motive: Unauthorized Access/Control # Root backdoor
  insertion_phase: distribution # Official source tarball replaced
  impact_type: Backdoor, Remote code execution
  references:
    - https://www.cert.org/historical/advisories/CA-1994-07.cfm # CERT Advisory
    - https://web.archive.org/web/20030804000609/http://www.team.net/mjb/hawp/hacks/wuftpd.html # Archive of initial findings
  historical_artifacts:
    - ftp://ftp.wustl.edu/packages/wuarchive-ftpd/wu-ftpd-2.2.tar.Z # Original compromised download location
    - ftp://ftp.cs.umn.edu/pub/wuftpd/wu-ftpd-2.2.tar.Z # Mirror potentially affected
  current_artifacts:
    - https://www.cert.org/historical/advisories/CA-1994-07.cfm # Advisory with technical details
    - https://web.archive.org/web/20030804000609/http://www.team.net/mjb/hawp/hacks/wuftpd.html # Analysis of the backdoor
  domain: ftp.wustl.edu
  domain_type: project download host
  artifact_type: source archive
  hashes:
    - md5:3e12b0efb95bcb97e5b58fb916323618 # Backdoored wu-ftpd-2.2.tar.Z
  versions:
    - 2.2 # wu-ftpd-2.2.tar.Z distribution file
