---
- id: gentoo
  title: Gentoo GitHub hack modified ebuilds
  synopsis: An attacker gained control of Gentoo's GitHub organization administrator
    account (reportedly 'risacher' via password guessing). The attacker modified content,
    including ebuilds for 'portage' and 'musl-dev' in the main Gentoo ebuild repository,
    replacing them with malicious versions designed to execute 'rm -rf /' which would
    attempt to remove all files from users' systems. Access was quickly regained and
    changes reverted.
  start_date: 2018-06-28
  end_date: 2018-06-28
  target:
    name: gentoo
    kind: distribution
    repo: https://github.com/gentoo
  actor:
    name: Individual Hacker
    kind: person
  language: Shell
  method:
    cause: compromised_account_credentials
    phase: source
    motive: disruption_protest
    transitive: false
  impact:
    types:
    - service_disruption
    - data_destruction
  artifacts:
  - id: gentoo
    name: gentoo
    ecosystem: github
    kind: revision_control_system
    website: https://github.com
    repo: https://github.com/gentoo
    start_date: 2018-06-28
    end_date: 2018-06-28
    locations:
    - uri: https://github.com/gentoo/gentoo/commit/b8ed5a815dfb8c077a92e6a3a90c1ae6a88d284d
      role: distribution
    - uri: https://github.com/gentoo-mirror/gentoo/archive/refs/heads/master.zip
      role: distribution
    - uri: https://wiki.gentoo.org/wiki/Github/2018-06-28_incident
      role: mirror
    - uri: https://security.gentoo.org/glsa/201807-01
      role: mirror
    hashes:
    - sha1:b8ed5a815dfb8c077a92e6a3a90c1ae6a88d284d
    - sha1:2bd555a1138cb197271e8ddeec38bf4c7ae71844
    commits:
    - b8ed5a815dfb8c077a92e6a3a90c1ae6a88d284d
    - 2bd555a1138cb197271e8ddeec38bf4c7ae71844
    notes:
    - Affected Gentoo scope covered various ebuilds and scripts hosted on GitHub at
      the time of compromise.
  references:
  - url: https://arstechnica.com/information-technology/2018/06/gentoo-linux-github-organization-hacked-and-defaced/
